## Data Source details for FLEXCUBE transactions

FCON.FJ.CONNPOOLED=Y
FCON.FJ.JNDI.NAME=jdbc/CBHOSTMntDataSource
FCON.FJ.USER=CBHOST
FCON.FJ.PASS={AES}1t3wtnz1FHgEGqgDAlHBkA\=\=
FCON.FJ.LDB.DRIVER=oracle.jdbc.OracleDriver
FCON.FJ.LDB.URL=jdbc\:oracle\:thin\:@CBSCORERSDCPROD.ARANAC.COM\:2020/UTKHCORE

#FCR 6.X Host database connection details with app id 'FC'
FCON.FC.CONNPOOLED=Y
FCON.FC.JNDI.NAME=jdbc/FCHOST_INDataSource
FCON.FC.USER=host  
FCON.FC.PASS={AES}1t3wtnz1FHgEGqgDAlHBkA\=\=
FCON.FC.LDB.DRIVER=oracle.jdbc.driver.OracleDriver
FCON.FC.LDB.URL=jdbc\:oracle\:thin\:@CBSRACUPG.ARANAC.COM\:1521\:UT3RACDB1

#Config for IL Reports
FCON.IL.CONNPOOLED=N
FCON.IL.JNDI.NAME=jdbc/@@DOMAIN_NAME@@DataSource
FCON.IL.USER=@@11X_IL_HOST_DB_USER_NAME@@
FCON.IL.PASS={AES}Sr+HCKB2EY9b0m67iabqQ6w/JHjC7NG55VMLBy0v90E\=
FCON.IL.LDB.DRIVER=oracle.jdbc.OracleDriver
FCON.IL.LDB.URL=@@11X_IL_DB_CONNECTION@@
BIP_DATASOURCE_NAME=BIPDB

## Data Source details for payments XA data source
FCON.FJ_XA.CONNPOOLED=Y
FCON.FJ_XA.JNDI.NAME=jdbc/FCBNEFTRTGSXADataSource
FCON.FJ_XA.LDB.DRIVER=oracle.jdbc.OracleDriver
FCON.FJ_XA.LDB.URL=jdbc\:oracle\:thin\:@CBSRACUPG.ARANAC.COM\:1521\:UT3BATCH1

## Data source details used for incoming payment validations
FCON.FJ_PM.CONNPOOLED=Y
FCON.FJ_PM.JNDI.NAME=jdbc/FCBPMDataSource
FCON.FJ_PM.LDB.DRIVER=oracle.jdbc.OracleDriver
FCON.FJ_PM.LDB.URL=jdbc\:oracle\:thin\:@CBSRACUPG.ARANAC.COM\:1521\:UT3BATCH1

## Data Source details for Archival Database
FCON.FJ_ARC.CONNPOOLED=Y
FCON.FJ_ARC.JNDI.NAME=jdbc/FCHOST_INDataSource
FCON.FJ_ARC.USER=host
FCON.FJ_ARC.PASS={AES}1t3wtnz1FHgEGqgDAlHBkA\=\=
FCON.FJ_ARC.LDB.DRIVER=oracle.jdbc.OracleDriver
FCON.FJ_ARC.LDB.URL=jdbc\:oracle\:thin\:@CBSRACUPG.ARANAC.COM\:1521\:UT3BATCH1

## RAC Settings: INST1,INST2 are database instances mentioned in nam_dbinstance column of ba_eod_ctrl_param. 	
#FCON.FJ.INST1.JNDI.NAME=jdbc/FCHOST_INDataSource
#FCON.FJ.INST2.JNDI.NAME=jdbc/FCHOST_INDataSource
FCON.FJ.PROD.JNDI.NAME=jdbc/FCHOST_INDataSource
FCON.FJ.REP.JNDI.NAME=jdbc/FCHOST_INDataSource
#Alert Datasource configuration, ALRTDISP is configured as naminstance in alert.properties
FCON.FJ.ALRTDISP.JNDI.NAME=jdbc/FCHOST_INDataSource

## OLTP JMS Details  
FCRJ.HOST_Q_FACT=jms/FCBOltpQM
FCRJ.HOST_RES_Q=jms/FCBOltpResponseQ

## Report Details
FCRJ.HOST_REPORT_QCF=jms/FCBReportsQM
FCRJ.HOST_REPORT_REQ_Q=jms/FCBReportsRequestQ
FCR.REPORTPATH=${user.home}/../../rpt
FCR.FLG_ABORT_ON_FAILD_REPORT=true
FCR.FLG_COMPRESS_REPORT_FILE=true
FCR.REPOUT=${user.home}/../rjsout
FCRJ.RJSOUTHTML=http\:///runarea/rjsout
FCR.ADHOCREPOUT=${user.home}/../rjsout/

## Channels
FCRJ.CHANNEL_REQ_Q=jms/FCBChannelRequestQ
FCRJ.CHANNEL_Q_FACT=jms/FCBChannelQM
FCRJ.CHANNEL_RES_Q=jms/FCBChannelResponseQ

## Batch - jndi names
FCRJ.BT.JNDI_SR_QCF=jms/FCBBatchQM
FCRJ.BT.JNDI_SR_Q=jms/FCBBatchShellQ
FCRJ.BT.JNDI_RP_QCF=jms/FCBBatchQM
FCRJ.BT.JNDI_RP_Q=jms/FCBBatchResponseQ
FCRJ.BT.JNDI_FW_QCF=jms/FCBBatchQM
FCRJ.BT.JNDI_FW_Q=jms/FCBBatchFrameQ
FCRJ.BT.JNDI_RQ_Q=jms/FCBBatchRequestQ

## Online Gl Posting - jndi names
FCRJ.GL_POST.JNDI_QCF=jms/FCBBatchQM
FCRJ.GL_POST.JNDI_Q=jms/FCBGlPostingQ

## DATABASE OBJECT GENERATOR xsl properties
FCRJ.DBOBJXSL.AREA=${user.home}/../xsl
FCRJ.DBOBJSRC.AREA=${user.home}/../DB_OBJECT

## Connection Factory To Be used.
# WLS---Web Logic Server(WLInitialContextFactory)
#QCF_USED=weblogic.jndi.WLInitialContextFactory
#QCF_PAY_EXT=weblogic.jndi.WLInitialContextFactory
QCF_USED=com.sun.jndi.fscontext.RefFSContextFactory
QCF_PAY_EXT=com.sun.jndi.fscontext.RefFSContextFactory
##Below property will be used in IMPS txns
QCF_IMPS_EXT=weblogic.jndi.WLInitialContextFactory

##Below Parameter is identifies JDK inplementation
#For an IMB JDK implementation, value for the below property should be set as
#JDK_IMPL = IBMJDK and for Oracle JDK value should be set as JDK_IMPL = OJDK
#Default implementation considered is Oracle JDK
JDK_IMPL=IBMJDK

# IBMMQ---IBM Web Sphere MQ(MQQueueFactory)
#QCF_USED=com.ibm.mq.jms.context.WMQInitialContextFactory
QCF_PAY_EXT=com.sun.jndi.fscontext.RefFSContextFactory

